name: 'facebook_pages_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  post_history: "{{ ref('facebook_pages_post_history_data') }}"
  page: "{{ ref('facebook_pages_page_data') }}"
  lifetime_post_metrics_total: "{{ ref('facebook_pages_lifetime_post_metrics_total_data') }}"
  daily_page_metrics_total: "{{ ref('facebook_pages_daily_page_metrics_total_data') }}"

seeds:
  facebook_pages_source_integration_tests:
    facebook_pages_post_history_data:
      +column_types:
        id: string
        promotable_id: string
    facebook_pages_lifetime_post_metrics_total_data:
      +column_types:
        post_id: string